[package]
name = "web-thread-shim"
version = "0.1.0"
edition = "2024"

authors.workspace = true
license.workspace = true
repository.workspace = true

[lints.clippy]
pedantic = "warn"

[dependencies]
futures = "0.3.31"
thiserror = "2.0.17"
